Repository TsubakiBotPad/misc-cogs, pull requests merged in 2021-06, with the labels that each got.

#170 Read child menu type dynamically from ims
  menulistener/menulistener.py
Labels: enhancement

#187 Gate onlineplot commands
  onlineplot/onlineplot.py
Labels: onlineplot

#195 [OnlinePlot] Don't start the loop twice
  onlineplot/__init__.py
  onlineplot/onlineplot.py
Labels: bug
